language: objective-c
osx_image: xcode10.1

install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter

script:
  - xcodebuild clean build -project Kelvin.xcodeproj -scheme CommandLine -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -quiet
  - xcodebuild \
  -workspace Kelvin.xcworkspace \
  -scheme KelvinTests \
  -destination "platform=macOS" \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  test | xcpretty -f `xcpretty-travis-formatter`; exit ${PIPESTATUS[0]}
